[build]
  command = "npm run build"
  publish = ".next"
  functions = "out_functions"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Required for Next.js 13+ with the App Router
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs"]

# Required for Next.js image optimization
[[redirects]]
  from = "/_next/image"
  to = "/.netlify/builders/_next/image"
  status = 200
  force = true
