# Netlify configuration for Next.js app located in the frontend/ subdirectory

[build]
  base = "frontend"
  command = "npm run build:static"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  BACKEND_URL = "https://lumina-nbzx.onrender.com"
  NEXT_PUBLIC_BACKEND_URL = "https://lumina-nbzx.onrender.com"
  NEXT_PUBLIC_API_URL = "https://lumina-nbzx.onrender.com"
