"""add_is_archived_to_chat_sessions

Revision ID: eb4c3129a20c
Revises: ac434985c1ec
Create Date: 2025-07-20 21:10:16.621342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4c3129a20c'
down_revision: Union[str, Sequence[str], None] = 'ac434985c1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('chat_messages', sa.Column('session_id', sa.Integer(), nullable=True))
    
    # Only update existing messages if sessions exist
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM chat_sessions LIMIT 1) THEN
                UPDATE chat_messages SET session_id = (SELECT id FROM chat_sessions LIMIT 1);
            END IF;
        END
        $$;
    """)
    
    # Only set NOT NULL if we updated all records
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM chat_messages WHERE session_id IS NULL) THEN
                ALTER TABLE chat_messages ALTER COLUMN session_id SET NOT NULL;
            END IF;
        END
        $$;
    """)
    
    # Add the foreign key constraint if session_id is populated
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM chat_messages WHERE session_id IS NULL) THEN
                ALTER TABLE chat_messages ADD CONSTRAINT fk_chat_messages_session 
                FOREIGN KEY (session_id) REFERENCES chat_sessions(id);
            END IF;
        END
        $$;
    """)
    
    # Drop old column and index
    op.drop_index(op.f('ix_chat_messages_chat_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'chat_id')
    
    # Add the is_archived column
    op.add_column('chat_sessions', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'is_archived')
    op.add_column('chat_messages', sa.Column('chat_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_index(op.f('ix_chat_messages_chat_id'), 'chat_messages', ['chat_id'], unique=False)
    op.drop_column('chat_messages', 'session_id')
    # ### end Alembic commands ###
